### PR TITLE
Merge with the dev replicas repo.

### PR DESCRIPTION
**Pull request by jasonhawkharris**
Adds terraform configs from [sourcegraph/terraform-dev-replicas](https://github.com/sourcegraph/terraform-dev-replicas). These configs deploy a Kubernetes cluster to either GCP or AWS with a Sourcegraph instance built in.

### CODE REVIEW

**Comment by beyang** [comment]
How should a reader of this repository reason about these directories relative to the other ones that exist?

**Comment by jasonhawkharris** [comment]
I don't know why this is re-opened. I had it closed so I could make an update to the readme's first. Closing again. I'll tag you for a review when I'm done with the README's.

**Comment by beyang** [comment]
Does it make sense to include these other clusters in this repository, or will users get confused when they land here from elsewhere in the docs? Like, we don't actually want customers to take a dependency on the sg-on-terraform configs here, do we?

**Comment by jasonhawkharris** [comment]
Maybe it would be better to have a separate heading in the readme that mentions the dev-replicas repo, and a separate heading in the dev-replicas README.md for this repo.

Something like...

## Deploy a cluster + Sourcegraph
If you'd like to deploy a cluster with Sourcegraph already installed, you can use the examples in our `sourcegraph/dev-replicas` repo.

and in the dev replicas repo...

## Deploying a cluster only
If you'd like to deploy your cluster without a Sourcegraph instance, you can use the examples in our `sourcegraph/tf-k8s-configs`


Or we could just avoid having them linked all together and close this up.

**Comment by beyang** [comment]
Closing for staleness. Please re-open if still relevant.

**Pull request closed without merging**
